apiVersion: batch/v1
kind: Job
metadata:
  name: keycloak-create-public-client
  namespace: keycloak
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: kcadm
          image: quay.io/keycloak/keycloak:24.0.5
          envFrom:
            - secretRef:
                name: keycloak-admin
          command: ["/bin/bash","-c"]
          args:
            - |
              set -e
              until /opt/keycloak/bin/kcadm.sh config credentials --server http://keycloak.keycloak.svc.cluster.local \
                --realm master --user ${KEYCLOAK_ADMIN} --password ${KEYCLOAK_ADMIN_PASSWORD}; do sleep 3; done
              echo "Ensuring public client lab-public in realm lab..."
              if ! /opt/keycloak/bin/kcadm.sh get clients -r lab -q clientId=lab-public | grep -q '"id"'; then
                /opt/keycloak/bin/kcadm.sh create clients -r lab \
                  -s clientId=lab-public -s enabled=true -s protocol=openid-connect \
                  -s publicClient=true -s standardFlowEnabled=true -s directAccessGrantsEnabled=true \
                  -s redirectUris='["http://localhost:8088/*","http://keycloak.local/*"]'
              fi
              echo "Done."


