apiVersion: apps/v1
kind: Deployment
metadata:
  name: rust-api
  namespace: k3s-lab
  labels:
    app: rust-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rust-api
  template:
    metadata:
      labels:
        app: rust-api
    spec:
      containers:
      - name: rust-api
        image: docker.io/library/k3s-lab-api:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: rust-api-config
              key: DATABASE_URL
        - name: RUST_LOG
          valueFrom:
            configMapKeyRef:
              name: rust-api-config
              key: RUST_LOG
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: rust-api-config
              key: PORT
        - name: JWT_SECRET
          valueFrom:
            configMapKeyRef:
              name: rust-api-config
              key: JWT_SECRET
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: rust-api-service
  namespace: k3s-lab
spec:
  selector:
    app: rust-api
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP
