apiVersion: v1
kind: ConfigMap
metadata:
  name: rust-api-config
  namespace: k3s-lab
  labels:
    app: rust-api
data:
  # Database Configuration
  DATABASE_URL: "postgresql://postgres:password123@postgres-service:5432/k3s_lab"
  
  # Application Configuration
  RUST_LOG: "info"
  RUST_BACKTRACE: "1"
  PORT: "8080"
  
  # JWT Configuration
  JWT_SECRET: "your-super-secret-jwt-key-change-this-in-production-12345"
  JWT_EXPIRATION_HOURS: "24"
  
  # API Configuration
  API_HOST: "0.0.0.0"
  API_PORT: "8080"
  
  # CORS Configuration
  CORS_ORIGIN: "*"
  CORS_METHODS: "GET,POST,PUT,DELETE,OPTIONS"
  CORS_HEADERS: "Content-Type,Authorization"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: k3s-lab
  labels:
    app: postgres
data:
  # PostgreSQL Configuration
  POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
  POSTGRES_HOST_AUTH_METHOD: "md5"
  
  # Performance Tuning
  shared_buffers: "256MB"
  effective_cache_size: "1GB"
  maintenance_work_mem: "64MB"
  checkpoint_completion_target: "0.9"
  wal_buffers: "16MB"
  default_statistics_target: "100"
