name: build-and-push
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: docker
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build binary (release)
        run: |
          cargo build --release

      - name: Build Docker image
        run: |
          docker build -t localhost:5000/hello-world-app:latest .

      - name: Push Docker image to local registry
        run: |
          docker push localhost:5000/hello-world-app:latest
