apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world-app
  namespace: argocd
  labels:
    app: hello-world
spec:
  project: default
  source:
    repoURL: http://gitea.gitea.svc.cluster.local:3000/gitea-admin/hello-world-app.git
    targetRevision: HEAD
    path: k8s/test-app
  destination:
    server: https://kubernetes.default.svc
    namespace: test-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
  revisionHistoryLimit: 10
