apiVersion: v1
kind: Namespace
metadata:
  name: test-app
  labels:
    app: hello-world
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  namespace: test-app
  labels:
    app: hello-world
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: nginx:alpine
        ports:
        - containerPort: 80
        env:
        - name: MESSAGE
          value: "Hello from GitOps Pipeline! 🚀"
        command: ["/bin/sh"]
        args:
        - -c
        - |
          echo '<html><body><h1>Hello from GitOps Pipeline! 🚀</h1>
          <p>This app was deployed via GitOps!</p>
          <p>Deployed at: '$(date)'</p>
          <p>Namespace: test-app</p>
          <p>Pod: '$(hostname)'</p>
          </body></html>' > /usr/share/nginx/html/index.html
          nginx -g 'daemon off;'
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world
  namespace: test-app
  labels:
    app: hello-world
spec:
  selector:
    app: hello-world
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-world
  namespace: test-app
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: hello-world.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hello-world
            port:
              number: 80
